config/routes.rb
Rails.application.routes.draw do
  # devise_scope :user do
  #   root to: "users/sessions#new"
  # end
  
  # devise_for :users, controllers: { 
  #   registrations:  'users/registrations',
  #   sessions:  'users/sessions'
  # }

  # root  'users#home'
  root 'users/sessions#new'
  get   'users', to: 'users#dashboard', as: :dashboard
  post  'users', to: 'users#dashboard', as: :user
  get   'logout', to: 'users#logout', as: :logout

  # get '/cubes', to: 'cubes#cube'
  get '/cubes/room', to: 'cubes#room'
  get '/fetch_html', to: 'users/rooms#fetch_html'
  get '/verify_image_url', to: 'users/rooms#verify_image_url'

  resources :users, path: 'accounts', only: [] do
    collection do
      get :profile
      get 'profile/:user_id', to: 'users#show'
      get 'edit/profile', to: "users#edit"
      get :cubes
      get :get_country_code
    end
  end

  namespace :users, path: 'accounts' do
    match 'sign_in', to: 'sessions#new', via: :get
    match 'sign_up', to: 'registrations#new', via: :get

    resources :registrations, path: '', only: [] do
      collection do
        post  :profile
        get   :forgot_password
      end
    end

    resources :rooms, path: '', only: :[] do
      collection do 
        get :team_room
        match 'cubes/:cube_id', to: 'rooms#first_room', via: :get
      end
    end
  end

  namespace :a_frames do
    get :frame_test
    get :test_frame_list
  end
end

app/views/layouts/_footer.html.haml
%section.section-3.row.container
  .col-sm-12.text-center.text-uppercase
    %ul.list-inline
      / %li.title
      /   %a.Footer-nav-item{:href => root_path} PINCUBED
      / %li.title
      /   %a.Footer-nav-item{:href => "https://www.collabrjabbr.com/"} COLLABRJABBR
      / %li.title
      /   %a.Footer-nav-item{:href => "http://www.thematics.net", :target => "_blank"} THEMATICS
      %li.title
        %a.Footer-nav-folder-item{:href => "https://www.seamlessintegrateddynamics.com/"} SINDY.IO
  .col-sm-12.text-center
    %ul.list-inline.social-media-bottom
      %li.title
        %a{href: 'https://twitter.com/CollabRjabbR'}
          %i.fa.fa-twitter
      %li.title
        %a{href: 'https://www.facebook.com/charles.kirby.750'}
          %i.fa.fa-facebook
      %li.title
        %a{href: 'https://www.youtube.com/channel/UCuSgh2VO_Doq8I9f3lbMBGA'}
          %i.fa.fa-youtube-play
  /     %li
  /       %a Home
  /     %li
  /       %a Sign Up
  /     %li
  /       %a About
  /     %li
  /       %a Investor Resaltions
  / .col-sm-4
  /   %ul.list-unstyled
  /     %li.title Blogs and Community
  /     %li
  /       %a PinCUBED Blog
  /     %li
  /       %a Facebook
  /     %li
  /       %a Instagram
  /     %li
  /       %a Twitter
  /     %li
  /       %a Youtube
  / .col-sm-4
  /   %ul.list-unstyled
  /     %li.title Support
  /     %li
  /       %a Community Forum
  /     %li
  /       %a FAQ
  /     %li
  /       %a Contact PinCUBED
  /     %li
  /       %a Downloads

app/views/layouts/_header.html.haml
.page-topbar
  .logo-area
    %a{href: "/"}
      = image_tag(image_path('sindycubes_square_logo'))
    / = image_tag(image_path('pin3dlogo'))
    / %a{href: "/"}
    /   = image_tag(image_path('sindylogo'))
    / %a{href: "http://www.collab101.org/home-page-dashboard"}
    /   = image_tag(image_path('k-logo'))
    / %a{href: "http://www.xrportfolio.space/"}
    /   = image_tag(image_path('colla-xr-logo'))
    / %a{href: "https://www.seamlessintegrateddynamics.com/pincube-app-splash"}
    /   = image_tag(image_path('3check-logo'))
    / %a{href: "https://www.harknessiroom.com/"}
    /   = image_tag(image_path('infinity-logo'))
    / %a{href: "https://www.harknessiroom.com/"}
    /   = image_tag(image_path('harkn-logo'))
    / PIN
    / %sup{style: "left: -0.3em;margin-right: -0.5em;"}3
  .quick-area
    .pull-left
      %ul.info-menu.left-links.list-inline.list-unstyled
        - if controller.action_name != 'home'
          / %li.sidebar-toggle-wrap
          /   %a.sidebar_toggle{"data-toggle" => "sidebar", :href => "#"}
          /     %i.fa.fa-bars

          %li.notify-toggle-wrapper#all-notifs{style: "display:none;"}
            %a.toggle{"data-toggle" => "dropdown", :href => "#", 'aria-expanded'=>"true"}
              %i.fa.fa-bell
              %span.badge.badge-accent#tot-notif-count.tot-notif-count 0
            %ul.dropdown-menu.notifications.animated.fadeIn
              %li.total
                %span.small
                  You have
                  %strong.tot-notif-count 0
                  new notifications.
                  / %a.pull-right{:href => "javascript:;"} Mark all as Read
              %li.list
                / {style: "height: 80px;"}
                %ul.dropdown-menu-list.list-unstyled.ps-scrollbar
                  %li.unread.offline.coll-requests{style: "display:none;"}
                    / available: success, warning, info, error
                    %a{"data-toggle" => "modal", :href => "#cmpltadminModal-7"}
                      .notice-icon
                        %i.fa.fa-user
                      %div
                        %span.name{style: 'padding-top: 7px;'}
                          %strong Collaboration Requests

              %li.external
                %a{:href => "javascript:;"}
                  %span All Notifications




    - home_class = action_name == 'home' ? 'un-auth' : ''
    .pull-right
      %ul.info-menu.right-links.list-inline.list-unstyled{class: "#{home_class}"}
        -if action_name == "profile"
          %li.logout.showopacity{style: 'display: none;'}
            = link_to('FIND COLLABORATOR', nil, style: 'color: white;text-decoration: none;')

        -if action_name == "cubes" || (action_name == "dashboard" || action_name == "user" ) || (action_name == "show" && controller_name == "users") || action_name == "edit" || action_name == "first_room" || action_name == "home"
          %li.logout.showopacity{style: 'display: none;'}
            
            / = link_to('PROFILE', profile_users_path, action: 'replace', style: 'color: white;text-decoration: none;')

            -url_origin = if Rails.env == "production"
              -'https://portfolio.sindyxr.com'
            -else
              -'http://localhost:3000'

            = link_to('PROFILE', "#{url_origin}/users/register/profile/dashboard", action: 'replace', style: 'color: white;text-decoration: none;')
        -if action_name != "home"
          %li.logout.showopacity{style: 'display: none;'}
            %a#theme{href:'', style: 'color: white;text-decoration: none;'} THEME
        
        / -if action_name == "profile" || (action_name == "dashboard" || action_name == "user" ) || (action_name == "show" && controller_name == "users")|| action_name == "edit" || action_name == "home"
        %li.logout.showopacity{style: 'display: none;'}
          = link_to('GRID', cubes_users_path, id: "", style: 'color: white;text-decoration: none;')
            
        %li.logout.showopacity{style: 'display: none;'}
          = link_to('HELP', nil, id: "", style: 'color: white;text-decoration: none;')

        %li.logout.showopacity{style: 'display: none;'}
          = link_to('LOG OUT', nil, id: "logout_user", style: 'color: white;text-decoration: none;')
        / %li.sign-in.showopacity{style: 'display: none;'}
        /   = link_to('Sign In', users_sign_in_path, style: 'color: white;text-decoration: none;')
        / %li.separator
        %li.register.showopacity{style: 'display: none;'}
          = link_to('SIGN IN', users_sign_in_path, style: 'color: white;text-decoration: none;font-size: 13px;')
        %li#signup.register.showopacity{style: 'display: none;'}
          = link_to('SIGN UP', '#section-2-b', style: 'color: white;text-decoration: none;font-size: 13px;')

app/views/layouts/a_frames.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %title Test 360 Video
    %meta{:content => "360 Video — A-Frame", :name => "description"}/
  
    %script{:src => "https://aframe.io/releases/0.9.2/aframe.js"}
  %body
    = yield

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SindyCUBEs
    / = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    / = javascript_include_tag 'application', 'data-turbolinks-track' => true
    / = render 'layouts/includes/header_includes'
    = csrf_meta_tags

    = javascript_include_tag "https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js", media: 'all'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true
    = javascript_include_tag 'application', 'data-turbolinks-track'=> true
    = javascript_include_tag 'https://unpkg.com/dropbox/dist/Dropbox-sdk.min.js'
    = javascript_include_tag 'users/' + controller_name, media: 'all', 'data-turbolinks-track': true
    = stylesheet_link_tag    'users/' + controller_name, media: 'all', 'data-turbolinks-track': true
    = render 'layouts/includes/header_includes'
  %body
    = yield
    = render 'layouts/includes/bottom_includes'

app/views/layouts/users.html.haml
!!!
%html
  %head
    %meta{:content => "reload", :name => "turbolinks-visit-control"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SindyCUBEs
    = csrf_meta_tags
    / - if controller.action_name != 'cube' && controller.action_name != 'room'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    / = javascript_include_tag 'users/' + controller_name, media: 'all', 'data-turbolinks-track': false
    = stylesheet_link_tag     controller_name, media: 'all', 'data-turbolinks-track': "reload"
    
    = render 'layouts/includes/header_includes'
  %body
    .bg-overlay
    - if (controller.action_name != 'cube' && controller.action_name != 'room')
      = render "layouts/header"
    .page-container.row-fluid.container-fluid
      - if controller.action_name == 'cubes' || controller_name == 'rooms'
        = render "layouts/sidebar"
      = yield

      / = render 'layouts/footer'
    .page-bottom
      = render 'layouts/includes/bottom_includes'
    = render 'layouts/modals/friend_requests'